spring.application.name=wedding-partner-app

#コンテキストパス
server.servlet.context-path=/
server.port=8080

#DB設定
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.encoding=utf-8

#mybatis設定
mybatis.mapper-locations=classpath:com/example/weddingpartnerapp/repository/*.xml
mybatis.type-aliases-package=com.example.weddingpartnerapp.model
logging.level.com.example=debug

#メール設定
spring.mail.host=smtp.gmail.com
#ポートは465番
spring.mail.port=465
spring.mail.username=huluaaa521@gmail.com
spring.mail.password=noknzunlxtjzmrub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

#URL(本番用)
local.mail.url=https://weddingpartnerapp.onrender.com
