spring.application.name=wedding-partner-app

#コンテキストパス
server.servlet.context-path=/WeddingPartnerApp
server.port=8080

#DB設定
spring.datasource.url=jdbc:postgresql://localhost:5432/weddingpartnerapp_db
spring.datasource.username=postgres
spring.datasource.password=pgsql
spring.datasource.driver-class-name=org.postgresql.Driver
spring.sql.init.encoding=utf-8

#mybatis設定
mybatis.mapper-locations=classpath:com/example/weddingpartnerapp/repository/*.xml
mybatis.type-aliases-package=com.example.weddingpartnerapp.model
logging.level.com.example=debug

#メール設定
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=huluaaa521@gmail.com
spring.mail.password=noknzunlxtjzmrub
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#URL(ローカル用)
local.mail.url=http://localhost:8080/WeddingPartnerApp
