--自動採番初期化する場合
ALTER TABLE 'テーブル' ALTER COLUMN '列' RESTART WITH 1;
--ユーザ
CREATE TABLE IF NOT EXISTS users (
	user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_name VARCHAR(255),
	mail_address VARCHAR(100),
   password VARCHAR(255),
   role VARCHAR(10),
   salt bytea
);
--顧客
CREATE TABLE IF NOT EXISTS customers (
 customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id          INTEGER,
 groom_name VARCHAR(50),
 bride_name VARCHAR(50),
 mail_address     VARCHAR(100),
 phone_number     VARCHAR(20),
 FOREIGN KEY (user_id) REFERENCES users(user_id)
);
--ToDo
CREATE TABLE IF NOT EXISTS todos (
 todo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id		INTEGER,
 status 			BOOLEAN,
 task_content  	VARCHAR(100),
 deadline 			DATE,
 delete_flag  		BOOLEAN,
 FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
--式
CREATE TABLE IF NOT EXISTS weddings (
 wedding_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id		INTEGER,
 venue_id			INTEGER,
 wedding_date 		DATE,
 completed_flag 	BOOLEAN,
 FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
 FOREIGN KEY (venue_id) REFERENCES venues(venue_id)
);
--ゲスト
CREATE TABLE IF NOT EXISTS guests (
 guest_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 wedding_id		INTEGER,
 guest_name 		VARCHAR(100),
 mail_address      VARCHAR(100),
 precaution		VARCHAR(255),
 attendance		BOOLEAN,
 ans_flag			BOOLEAN,
 delete_flag		BOOLEAN,
 FOREIGN KEY (wedding_id) REFERENCES weddings(wedding_id)
);
--アレルギー
CREATE TABLE IF NOT EXISTS allergies (
 allergy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 allergy_name 		VARCHAR(255)
);
--ゲストアレルギー
CREATE TABLE IF NOT EXISTS guests_allergies (
 guest_allergy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 guest_id			INTEGER,
 allergy_id		INTEGER,
 FOREIGN KEY (guest_id) REFERENCES guests(guest_id),
 FOREIGN KEY (allergy_id) REFERENCES allergies(allergy_id)
);
--会場
CREATE TABLE IF NOT EXISTS venues (
 venue_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 venue_name 		VARCHAR(100),
 phone_number 		VARCHAR(20),
 venue_amount		INTEGER
);
--式タイプ
CREATE TABLE IF NOT EXISTS wedding_types (
 wedding_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 wedding_type_name 		VARCHAR(10),
 wedding_type_amount		INTEGER
);
--会場-式タイプ
CREATE TABLE IF NOT EXISTS venues_wedding_types (
 venue_wedding_type_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 venue_id			INTEGER,
 wedding_type_id		INTEGER,
 FOREIGN KEY (venue_id) REFERENCES venues(venue_id),
 FOREIGN KEY (wedding_type_id) REFERENCES wedding_types(wedding_type_id)
);
--料理
CREATE TABLE IF NOT EXISTS dishes (
 dish_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 dish_amount 		INTEGER
);
--ドリンク
CREATE TABLE IF NOT EXISTS drinks (
 drink_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 drink_amount 		INTEGER
);
--新郎ドレス
CREATE TABLE IF NOT EXISTS groom_dresses (
 groom_dress_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 groom_dress_amount 		INTEGER
);
--新婦ドレス
CREATE TABLE IF NOT EXISTS bride_dresses (
 bride_dress_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 bride_dress_amount 		INTEGER
);
--オプション金額
CREATE TABLE IF NOT EXISTS option_amount (
 option_amount_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 photoshoot_amount 		INTEGER,
 videoshoot_amount 		INTEGER,
 flower_arrangement_amount INTEGER,
 gift_amount				INTEGER,
 acoustic_amount			INTEGER,
 hair_makeup_amount		INTEGER,
 moderator_amount			INTEGER,
 cake_amount				INTEGER
);	
--契約
CREATE TABLE IF NOT EXISTS contracts (
 contract_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_id       INTEGER,
 numofperson		INTEGER,
 venue_name		VARCHAR(50),
 wedding_type		VARCHAR(10),
 wedding_date		DATE,
 dish  			INTEGER,
 drink				INTEGER,
 groom_dress	    INTEGER,
 bride_dress      	INTEGER,
 photoshoot_flg    BOOLEAN,
 videoshoot_flg    BOOLEAN,
 flower_arrangement_flg    BOOLEAN,
 gift_flg    		BOOLEAN,
 acoustic_flg      BOOLEAN,
 hair_makeup_flg   BOOLEAN,
 moderator_flg     BOOLEAN,
 other_text	    VARCHAR(255),
 total_amount		INTEGER,
 completed_flg		BOOLEAN,
 FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
